add_newline = false

[cmd_duration]
style = 'bold gray'

[git_branch]
symbol = ''
style = 'purple'
format = 'on [${symbol} ${branch}(:$remote_branch) ]($style)'

[git_status]
style = 'red'
modified = ''
untracked = ''
stashed = '󰜦'
format = '([\[$all_status$ahead_behind\]]($style) )'

[docker_context]
style = 'blue'
symbol = ''

[python]
style = 'yellow'
symbol = ''
format = '[${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[rust]
style = 'orange'
symbol = ''
format = '[${symbol} ${version}]($style)'

[lua]
style = 'blue'
symbol = ''
format = '[${symbol} ${version} ]($style)'

[nodejs]
style = 'green'
symbol = ''
format = '[${symbol} ${version}]($style)'

[golang]
style = 'cyan'
symbol = '󰟓'
format = '[${symbol} ${version}]($style)'

